Homework20: Vladislav Savchuk
VladislavSavchuk/pymar2024 pull request #10
Opened 2024-07-14 18:53 UTC by VladislavSavchuk

# Developed program tests from homework #11

- Bank deposit
- Library

1. Created a separate module for tests.
2. Imported functions from the module.
3. Wrote tests to check the application performance.
4. The tests check both positive and negative results.
5. The tests are run using _unittest_

2024-07-16 19:10 UTC, Stml89 requested changes

2024-07-16 19:10 UTC, Stml89 commented on homework/homework11/library.py
> +            return "reserved_success"
```suggestion
            return True
```

2024-07-16 19:10 UTC, Stml89 commented on homework/homework11/library.py
> +            return "taken_success"
```suggestion
            return True
```

2024-07-16 19:10 UTC, Stml89 commented on homework/homework11/bank_deposit.py
> +# print(deposit_person2.calculate_monthly_capitalization())
If you do not want to use something when module was imported - just use `if __name__ == __main__`. And start using logging module instead of `print`

2024-07-16 19:10 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        self.assertEqual(bank.rate, 3.5)
add some log that says that test was successful, e.g.:
`logger.info("Successfully verified  <.......>")`

2024-07-16 19:10 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        self.assertEqual(result, 1000.0)
3 different test cases?

2024-07-18 18:33 UTC, VladislavSavchuk commented
fixed according to the comments @Stml89

2024-07-18 20:33 UTC, Stml89 requested changes

2024-07-18 20:33 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        self.assertEqual(result, 1000.0)
Please divide this test into 3 TCs

2024-07-18 20:33 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        logger.info("Successfully verified bank attributes")
Nice

2024-07-18 20:33 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        self.assertEqual(result, 24417.91)
what is the diff between those 3 tests?

2024-07-18 20:33 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        self.assertNotEqual(result, 5000)
are they testing the case thing?

2024-07-18 20:33 UTC, Stml89 commented on homework/homework20/test_bank_deposit.py
> +        logger.info("Successfully verified bank attributes")
add the same for other TCs as well

2024-07-21 09:56 UTC, VladislavSavchuk commented
@Stml89
- corrected the tests based on your comments.
- divided the tests of boundary values into 3 separate test cases
- added Successfully logger to each test
- removed 2 unnecessary tests in test_calculate_monthly_capitalization that tested the same thing (my mistake)
- updated negative cases
It seems to be looking better now, thank you.

2024-07-23 19:27 UTC, Stml89 approved these changes

2024-07-23 20:35 UTC, merged